import React from "react";
import { FadeIn } from "@/hooks/use-scroll-spy";

export function Showcase() {
  const images = [
    { label: "Neural Topology", size: "col-span-1 row-span-1 md:col-span-2 md:row-span-2" },
    { label: "Data Refraction", size: "col-span-1 row-span-1" },
    { label: "Latent Space", size: "col-span-1 row-span-1" },
    { label: "Generative Flow", size: "col-span-1 row-span-1 md:col-span-2" },
  ];

  return (
    <section className="py-32 relative z-10">
      <div className="max-w-7xl mx-auto px-6">
        <FadeIn>
          <div className="mb-16">
            <h2 className="text-4xl font-bold mb-4">Glimpses of the Deep</h2>
            <p className="text-white/50 max-w-xl">
              Visual outputs generated by the core model, capturing the ethereal beauty of machine imagination.
            </p>
          </div>
        </FadeIn>

        <div className="grid grid-cols-1 md:grid-cols-4 md:grid-rows-2 gap-4 h-[800px] md:h-[600px]">
          {images.map((item, i) => (
            <FadeIn key={i} delay={i * 100} className={`${item.size} h-full`}>
              <div className="w-full h-full rounded-3xl glass border border-white/10 relative overflow-hidden group">
                
                {/* Simulated generated image background (gradient abstract for placeholder) */}
                <div className="absolute inset-0 bg-gradient-to-br from-background via-background to-white/5 opacity-80 z-0"></div>
                
                {/* Abstract shape generator based on index */}
                <div className={`absolute inset-0 z-10 transition-transform duration-700 group-hover:scale-105 opacity-60 ${
                  i === 0 ? 'bg-[radial-gradient(ellipse_at_center,_var(--tw-gradient-stops))] from-primary/30 via-transparent to-transparent' :
                  i === 1 ? 'bg-gradient-to-tr from-secondary/20 to-transparent' :
                  i === 2 ? 'bg-gradient-to-bl from-accent/30 to-transparent' :
                  'bg-[conic-gradient(at_bottom_right,_var(--tw-gradient-stops))] from-primary/20 via-secondary/10 to-transparent'
                }`}></div>

                {/* Noise texture overlay */}
                <div className="absolute inset-0 opacity-[0.03] z-20 mix-blend-overlay" style={{backgroundImage: 'url("data:image/svg+xml,%3Csvg viewBox=%220 0 200 200%22 xmlns=%22http://www.w3.org/2000/svg%22%3E%3Cfilter id=%22noiseFilter%22%3E%3CfeTurbulence type=%22fractalNoise%22 baseFrequency=%220.65%22 numOctaves=%223%22 stitchTiles=%22stitch%22/%3E%3C/filter%3E%3Crect width=%22100%25%22 height=%22100%25%22 filter=%22url(%23noiseFilter)%22/%3E%3C/svg%3E")'}}></div>
                
                <div className="absolute bottom-0 left-0 right-0 p-6 z-30 bg-gradient-to-t from-background/90 to-transparent transform translate-y-2 opacity-0 group-hover:translate-y-0 group-hover:opacity-100 transition-all duration-300">
                  <p className="text-sm font-mono tracking-wider text-white/80">{item.label}</p>
                </div>
              </div>
            </FadeIn>
          ))}
        </div>
      </div>
    </section>
  );
}
